world: ''
enabled: true
protect: true
entry-fee: ''
clear-wave-before-next: false
clear-boss-before-next: false
clear-wave-before-boss: false
lightning: true
auto-equip-armor: true
soft-restore: false
soft-restore-drops: false
require-empty-inv-join: false
require-empty-inv-spec: false
hellhounds: false
pvp-enabled: false
monster-infight: false
allow-teleporting: false
spectate-on-death: true
auto-respawn: true
share-items-in-arena: true
min-players: 0
max-players: 0
max-join-distance: 0
first-wave-delay: 5
wave-interval: 15
final-wave: 0
monster-limit: 100
monster-exp: false
keep-exp: true
food-regen: false
lock-food-level: true
spout-class-select: false
player-time-in-arena: world
auto-ignite-tnt: false
auto-start-timer: 0
auto-ready: false
use-class-chests: false
display-waves-as-level: false
display-timer-as-level: false
use-scoreboards: true
