# MobArena v0.0.0 - Config-file
# Read the Wiki for details on how to set up this file: http://goo.gl/F5TTc
# Note: You -must- use spaces instead of tabs!
global-settings:
    enabled: true
    allowed-commands: /list, /pl
    update-notification: true
classes:
    Knight:
        items: diamond_sword, potion:8197:3
        armor: 306,307,308,309
    Tank:
        items: iron_sword, potion:8229:2
        armor: 310,311,312,313
    Archer:
        items: wood_sword, bow, arrow:256, potion:8197:3, bone
        armor: 298,299,300,301
    Chemist:
        items: stone_sword, potion:16428:30, potion:16388:8, potion:16389:20, potion:8197:3, potion:8226:1
        armor: 314,315,316,317
    Oddjob:
        items: stone_sword, flint_and_steel, netherrack:2, tnt:4, potion:8197:3
        armor: 298,299,300,301
arenas:
    default:
        settings:
            world: world
            enabled: true
            protect: true
            entry-fee: ''
            clear-wave-before-next: false
            clear-boss-before-next: false
            clear-wave-before-boss: false
            lightning: true
            auto-equip-armor: true
            soft-restore: false
            soft-restore-drops: false
            require-empty-inv-join: false
            require-empty-inv-spec: false
            hellhounds: false
            pvp-enabled: false
            monster-infight: false
            allow-teleporting: false
            spectate-on-death: true
            auto-respawn: true
            share-items-in-arena: true
            min-players: 0
            max-players: 0
            max-join-distance: 0
            first-wave-delay: 5
            wave-interval: 15
            final-wave: 0
            monster-limit: 100
            monster-exp: false
            keep-exp: true
            food-regen: false
            lock-food-level: true
            spout-class-select: false
            player-time-in-arena: world
            auto-ignite-tnt: false
            auto-start-timer: 0
            auto-ready: false
            use-class-chests: false
            display-waves-as-level: false
            display-timer-as-level: false
            use-scoreboards: true
            isolated-chat: false
            global-first-join-announce: false
            global-end-announce: false
        waves:
            recurrent:
                def1:
                    type: default
                    priority: 1
                    frequency: 1
                    monsters:
                        zombies: 10
                        skeletons: 10
                        spiders: 10
                        creepers: 10
                        wolves: 10
                spec1:
                    type: special
                    priority: 2
                    frequency: 4
                    monsters:
                        powered-creepers: 10
                        zombie-pigmen: 10
                        angry-wolves: 10
                        blazes: 10
            single:
                swarm1:
                    type: swarm
                    wave: 6
                    monster: slime
                    amount: low
                boss1:
                    type: boss
                    wave: 10
                    monster: cave_spider
                    health: high
                    abilities: arrows, root-target, throw-nearby
        rewards:
            waves:
                every:
                    '3': feather, bone, stick
                    '5': dirt:4, gravel:4, stone:4
                    '10': iron_ingot:10, gold_ingot:8
                after:
                    '7': minecart, storage_minecart, powered_minecart
                    '13': iron_sword, iron_pickaxe, iron_spade
                    '16': diamond_sword
        class-limits:
            Archer: -1
            Oddjob: -1
            Chemist: -1
            Tank: -1
            Knight: -1