prefix: ''
world: ''
enabled: true
protect: true
entry-fee: ''
default-class: ''
clear-wave-before-next: false
clear-boss-before-next: false
clear-wave-before-boss: false
soft-restore: false
soft-restore-drops: false
require-empty-inv-join: false
require-empty-inv-spec: false
hellhounds: false
pvp-enabled: false
monster-infight: false
allow-teleporting: false
spectate-on-death: true
auto-respawn: true
share-items-in-arena: true
min-players: 0
max-players: 0
max-join-distance: 0
first-wave-delay: 5
wave-interval: 15
final-wave: 0
monster-limit: 100
monster-exp: false
food-regen: false
lock-food-level: true
player-time-in-arena: world
auto-ignite-tnt: false
auto-start-timer: 0
start-delay-timer: 0
auto-ready: false
use-class-chests: false
display-waves-as-level: false
display-timer-as-level: false
use-scoreboards: true
isolated-chat: false
global-join-announce: false
global-end-announce: false
show-death-messages: true