prefix: ''
world: ''
enabled: true
protect: true
entry-fee: ''
default-class: ''
clear-wave-before-next: false
clear-boss-before-next: false
clear-wave-before-boss: false
clear-wave-leeway: 0
soft-restore: false
soft-restore-drops: false
require-empty-inv-join: false
require-empty-inv-spec: false
pvp-enabled: false
monster-infight: false
allow-teleporting: false
spectate-on-death: true
auto-leave-on-end: false
share-items-in-arena: true
min-players: 0
max-players: 0
max-join-distance: 0
join-interrupt-timer: 0
first-wave-delay: 5
next-wave-delay: 0
wave-interval: 15
final-wave: 0
monster-limit: 100
monster-exp: false
keep-exp: false
food-regen: false
lock-food-level: true
player-time-in-arena: world
auto-ignite-tnt: false
auto-ignite-fuse: 80
auto-start-timer: 0
start-delay-timer: 0
auto-ready: false
use-class-chests: false
arena-warp-offset: 0
boss-health-bar: boss-bar
display-waves-as-level: false
display-timer-as-level: false
use-scoreboards: true
isolated-chat: false
announcer-type: title
global-join-announce: false
global-end-announce: false
show-death-messages: true
custom-reward-per-kill: false
custom-reward-per-kill-0-5: $5
custom-reward-per-kill-5-10: $7.5
custom-reward-per-kill-10+: $10